-- Generated from BACPAC on 2026-02-28
BEGIN;
TRUNCATE TABLE "AspNetRoleClaims", "AspNetUserClaims", "AspNetUserLogins", "AspNetUserRoles", "AspNetUserTokens", "Reviews", "Portfolios", "TouristAttractions", "AspNetUsers", "AspNetRoles", "__EFMigrationsHistory" RESTART IDENTITY CASCADE;
-- AspNetRoles
INSERT INTO "AspNetRoles" ("Id","ConcurrencyStamp","Name","NormalizedName") VALUES ('',NULL,NULL,NULL);
INSERT INTO "AspNetRoles" ("Id","ConcurrencyStamp","Name","NormalizedName") VALUES ('3fd8fa8b-b1c7-49b3-b20d-d827b0c5e044',NULL,'Local_company','LOCAL_COMPANY');
INSERT INTO "AspNetRoles" ("Id","ConcurrencyStamp","Name","NormalizedName") VALUES ('d052c60a-0c4d-49f9-aa0d-346499b6ae90',NULL,'Admin','ADMIN');
INSERT INTO "AspNetRoles" ("Id","ConcurrencyStamp","Name","NormalizedName") VALUES ('dcb58a84-3b9f-4566-b991-0858df135c21',NULL,'User','USER');
-- AspNetUsers
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('1548ed03-39e7-45c6-b435-37990961ea80',0,'6a3e07d4-7703-4e32-b950-7b1a7def1289','besiroviccm@gmail.com',true,true,true,NULL,'BESIROVICCM@GMAIL.COM','HOTEL_ELEMENTS','AQAAAAIAAYagAAAAEC26m8QsQ8mQToCLW+eIxLjV1P1xvyUtNpj9+MQ6rj4th9B/UDcFiAhujDCzyRBtUA==',NULL,false,'SWTBT6NGP2CBRRV3BX2BLBTWJ6UCTYVO',false,'hotel_elements');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('1c44ed34-5771-48d1-b028-1c3412024120',0,'5cf7f038-1edb-4f50-a4b0-bc48c2df95f2','besirovic.amina7@gmail.com',true,true,true,NULL,'BESIROVIC.AMINA7@GMAIL.COM','AMINA','AQAAAAIAAYagAAAAEBdxijYmmfxL4Ek4f9ljSZoT1MGUaaDiSKzFd439cuwO7W+dqZ78nuN4Zpq6zMtlFQ==',NULL,false,'OQZF6LZBB7CDWPDIAKKX2TQUH45WKKSE',false,'amina');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('74f6f9ee-ebfe-4755-b811-583449ae2397',0,'8f1c73a9-cd84-483c-b6db-dd45401169ea','besiroviccm@gmail.com',true,true,true,NULL,'BESIROVICCM@GMAIL.COM','ART','AQAAAAIAAYagAAAAEPCrcw5fVejpjYTqD5Ngz+N7cZ9VGDgncBi1aU12DVeNY9+4JqLfihZ6Gz6DGaZq7g==',NULL,false,'2EEQZGUXOHXMTQ376NXLP4AQ5HN67ETM',false,'art');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('785f4d30-7005-4b07-9ef5-a46c0cdd1db3',0,'18f65c25-9979-438e-853c-68e88c933e63','merisa@breyta.is',true,false,true,NULL,'MERISA@BREYTA.IS','TEST','AQAAAAIAAYagAAAAEFz3yzNabZC6Pp2y9fpd3bgcKgyRrsyPEHbbiejwrxR/JU66L1gvs5Xf1RjPsLwdpQ==',NULL,false,'W7RA7IZULLGUR6I3PBAGVIUOFQZUITV5',false,'test');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('8d7364c7-5526-4ed4-bb09-24114c811411',0,'f2f713d0-de85-4b7d-85a4-087f8afcdc74','besiroviccm@gmail.com',true,false,true,NULL,'BESIROVICCM@GMAIL.COM','ANISA','AQAAAAIAAYagAAAAEIwUvISURU3rBM1ULnHZ1tv6GPSoYQdSDUZSUZoh9WD0uVelhM6tjMDp959tcwFhVA==',NULL,false,'H5DFQOHCASPCXUU4SMCIPPU2ZK2YUCDB',false,'anisa');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('a4f6481f-223e-44fb-86ef-bd866e7dc1ea',0,'766b8006-286a-4739-9427-19f795246a61','besiroviccm@gmail.com',true,false,true,NULL,'BESIROVICCM@GMAIL.COM','MERISA','AQAAAAIAAYagAAAAEM300cNJ308H8px/isbifgSbELjqMZMmalSiGH2nOA6+wYXrCAggmJSqJejfkOg+vg==',NULL,false,'3MHNFECYA27O3GIPR3P2DI2QBCQ2DZOQ',false,'merisa');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('aa8988ae-bb40-424e-9654-4cfc04ceebf0',0,'0ef328d1-16e2-42a7-b613-a876ebe39718','besiroviccm@gmail.com',false,true,true,NULL,'BESIROVICCM@GMAIL.COM','PREDUZECE','AQAAAAIAAYagAAAAEFNrvcNUxAc6BUHfLm5JvZg93Zx4uIThkRKGKM13qqzGq2Zppj8EHJPp4E1VBY5Wgg==',NULL,false,'CFMLNY467N23K3PGITQ5FROSPXGUTFWR',false,'preduzece');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('e3cffb26-25f5-44e5-9680-2143844e4d5e',0,'5e07486a-5633-4880-8019-ecad3952dab5','besiroviccm@gmail.com',true,true,true,NULL,'BESIROVICCM@GMAIL.COM','VRBAK','AQAAAAIAAYagAAAAEL9/a/FyMFbBtRoV0lX49dv/keVbXul/bO9ZmIhY1rTvUqOFwhSvYU22sO7+wyOxlw==',NULL,false,'SZZBFMDNT2JJ3QV5FB2MSQ52W7PCHNC5',false,'vrbak');
INSERT INTO "AspNetUsers" ("Id","AccessFailedCount","ConcurrencyStamp","Email","EmailConfirmed","IsApproved","LockoutEnabled","LockoutEnd","NormalizedEmail","NormalizedUserName","PasswordHash","PhoneNumber","PhoneNumberConfirmed","SecurityStamp","TwoFactorEnabled","UserName") VALUES ('fe5c46d8-4c05-416e-bc7d-8b18ed674d86',0,'c6332393-55db-40a1-9b3b-9223166a4152','besiroviccm@gmail.com',true,true,true,NULL,'BESIROVICCM@GMAIL.COM','JAZZVA','AQAAAAIAAYagAAAAELuMgohOqZcd993obJA4L6rCpwh1OQjv3iYTSYbcyo3qlIhU0gfI9xzzjDNLi9gEhA==',NULL,false,'WKZ4Z37WOBFUENPNEJWCRANSJXMZKQ7T',false,'jazzva');
-- TouristAttractions
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (3,'hotel','Pobegnite u svet obnavljanja i mira u srcu Novog Pazara uz Aqua Spa Termalni Hotel. Smestite se usred prirodne lepote regije i pronađite savršeni utočište za opuštanje i revitalizaciju. Uživajte u našem Aqua Spa centru, gde termalne vode iz dubina zemlje pružaju jedinstveno iskustvo lečenja. Naše termalne bazeni, saune i terapeutske tretmane će vas osloboditi stresa i napetosti. Naš profesionalni tim se brine da vam pruži nezaboravno iskustvo wellnessa. Naše sobe su podjednako raskošne. Svaka soba i apartman su ukusno dizajnirani i nude spoj modernog luksuza i udobnosti. Probudite se uz predivne poglede na okolni pejzaž i uživajte u miru privatnih balkona i terasa. Aqua Spa Termalni Hotel nije samo mesto za relaksaciju, već i kulinaristička destinacija. Naš restoran nudi širok izbor lokalnih i internacionalnih jela, pripremljenih od najkvalitetnijih sastojaka. Smestite se u samom srcu Novog Pazara i istražite bogatu istoriju i kulturu grada. Izvan hotela čekaju vas lokalne atrakcije, pijace i istorijski spomenici koji čine Novi Pazar jedinstvenom destinacijom. Bilo da tražite romantični beg, wellness beg ili samo opuštanje tokom puta, Aqua Spa Termalni Hotel će premašiti vaša očekivanja. Dođite i doživite harmoniju prirode i luksuza u našem izvanrednom hotelu. Rezervišite svoj boravak danas i prepustite se putovanju opuštanja i obnove.','20.54956062516278','43.156206537146346','Aqua Spa Termale',NULL,'https://res.cloudinary.com/dp7iyoyad/image/upload/v1770649127/tourist_attractions/3/uxckblumedtexlcjtwni.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770725272/tourist_attractions/3/lkjijm0tclvnyi07uwjj.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770725989/tourist_attractions/3/jcae6wwzo9plzqpq6xo9.jpg',1);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (6,'hotel','Hotel M Star Novi Pazar se nalazi u Novom Pazaru i nudi smeštaj sa 4 zvezdice sa baštom, restoranom i barom. Hotel nudi besplatan WiFi i besplatan privatni parking. Hotel će gostima pružiti klimatizovane sobe sa radnim stolom, kuvalom za vodu, mini barom, sefom, TV-om ravnog ekrana i sopstvenom kupaonicom sa tušem. U hotelu M Star Novi Pazar svaka soba je opremljena posteljinom i peškirima. Gosti ovog smeštaja mogu uživati ​​u à la carte doručku. Oblast je popularna za vožnju bicikla, a u hotelu M Star Novi Pazar možete iznajmiti automobil. Na recepciji, gdje osoblje govori njemački, engleski, hrvatski i srpski, dostupno je 24 sata dnevno vodstvo.','20.52739200292262','43.15471869862287','Hotel M Star',NULL,'https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910778/tourist_attractions/6/f435ytofwwuq8gk8zfr2.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910779/tourist_attractions/6/qf1w8nk8u5wnetmuibvp.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910780/tourist_attractions/6/sudotlxsr5g4rxrxd8qb.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910780/tourist_attractions/6/sjwrn88s9y0fre1vzey2.jpg',4);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (18,'Islamic','Islamski centar Gazilar, otvoren 13. aprila 2021. godine, predstavlja pravo osvježenje u arhitekturi i istinski pečat postignuća Mešihata Islamske zajednice. Ovaj centar, najljepši i najmoderniji ne samo u Novom Pazaru i Sandžaku, već i šire, do Stambola, zrači modernom vizijom i duhovnom svrhom. Smješten na preko 50 ari površine, Islamski centar Gazilar ima dva ključna segmenta. Džamijski prostor se proteže na površini od hiljadu kvadrata, nudeći vjernicima prostor za molitvu koji je inspirisan tradicijom, ali opremljen suvremenim sadržajima. Druga cjelina centra, sa ukupnom površinom od hiljadu kvadratnih metara, obuhvata prostore za obrazovanje sa dvije učionice, restoran, kuhinju te četiri abdesthane – dvije za muškarce i dvije za žene. Osim toga, tu su i prostorije za gasulhanu, kao i praktične mogućnosti za pranje. Centar je također opremljen sa tri mjesta za obavljanje gasula, uz mogućnost kolskog pristupa i povezanosti sa gasulhanama i parkiralištem koje obuhvata 20 mjesta. Ukupno četiri ulaza, dva pješačka i dva za vozila, omogućavaju pristup iz različitih pravaca, sa opcijom korišćenja zasebnih ulaza za javnost i administrativne svrhe. Centralni minaret visine 37 metara ukrašava južni dio centra, a blizu njega se nalazi ulaz za multifunkcionalnu salu smještenu u suterenu. Tehnička opremljenost centra je impresivna, osiguravajući optimalne uslove tokom svih godišnjih doba. Zimi, sistem podnog i radijatorskog grijanja, podržan centralnom kotlarom na pelet, održava toplotu, dok se ljeti koristi centralni sistem hlađenja sa inovativnim fencoilerima u zidovima džamijskog prostora. Napredna informaciona tehnologija omogućava nadzor i organizaciju rada kroz fleksibilni prijenos zvuka i slike širom Centra. Ovaj moderni islamski centar, nazvan Gazilar, predstavlja sveobuhvatan podsjetnik na prošlost uz viziju budućnosti, mjesto gdje se obavlja molitva, edukacija i zajedništvo, i gdje se duhovni svijet prepliće sa savremenom tehnologijom.','20.523304858154862','43.128925112343104','Islamski centar Gazilar','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910959/tourist_attractions/18/qqjtincnojerhdpjbmne.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910960/tourist_attractions/18/dxmirfhqpkw8b8ecniqx.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910961/tourist_attractions/18/gtvhhu9qc5qxorqxg0a0.jpg',3);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (22,'Islamic','U istorijskoj Gazi Sinan-begovoj mahali, spomenutoj još 1528. godine, nalazi se džamija sa bogatom istorijom. Dr. Ejup Mušović predlaže da je Sinan-beg, zajedno sa svojim bratom Abdullahom, moguće bio vlasnik ili zakupac rudnika u Rogozni ili Gluhavici, akumulirajući veliko bogatstvo. Oni su velikodušno posvetili svoje bogatstvo i stekli slavu kao graditelji džamija i pripadajućih objekata. Smještena u srcu Sinan-begove mahale, džamija potiče iz vremena kada je područje brojalo 17 domaćinstava 1528. godine, kasnije smanjeno na 10 domaćinstava do 1540. godine, da bi se konačno razvilo u Sinan-begovu zajednicu do 1767. godine. Ova džamija, poput drugih u Novom Pazaru, pretrpela je razaranja i požare, naročito tokom Austro-turskog rata od 1683. do 1699. godine. Godine 1728. rekonstruisao ju je niški paša Osman Topal, postavši poznata kao Osman-pašina ili Nova džamija. Dodatno je oštećena do 1809. godine, ali je doživjela restauraciju krajem 19. veka. Nakon Drugog svetskog rata, komunističke vlasti su prenamenile džamiju u skladište, uzrokujući značajan propadanje. Uprkos izazovima, džamija je opstala i konačno prošla kroz značajnu restauraciju pre oko 20 godina, čuvajući svoju veličanstvenost. Njena karakteristična munara, jedna od najlepših u regionu, ostala je netaknuta. Džamijski kompleks sada uključuje Omladinski centar "Gazi Sinan-beg", sa multimedijalnim centrom, bibliotekom, salama za sastanke i kancelarijama, služeći edukaciji mladih u verskim, društvenim i kulturnim sferama.','20.51647340787177','43.13819237601934','Gazi Sinan-Begova džamija','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911093/tourist_attractions/22/h7eltfhqfmihbmdpeemp.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911095/tourist_attractions/22/krs0gjfku8ryuyylaowi.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911095/tourist_attractions/22/p2fqx71jvhedysj7u6sc.jpg',2);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (24,'christian','Dobrodošli u Petrovu Crkvu, dragulj srpske istorije u Novom Pazaru. Sa punim imenom, Crkva Svetih apostola Petra i Pavla, Petrova Crkva predstavlja najstariji spomenik crkvene arhitekture u Srbiji i prvobitno je bila sedište Raska eparhije. Nalazi se samo 2 km severno od centra Novog Pazara, u naselju Deževski put, odnosno Postenje. Ova crkva ima osnovu rotunde sa upisanim četvorolistom i potiče iz vremena Vizantije, dok freske iznutra datiraju iz 10., 12. i 13. veka. Na mestu gde se sada nalazi crkva nekada je stajao rano-hrišćanski objekat podignut u 7. veku. Tokom arheoloških iskopavanja unutar crkve, pronađena je kolekcija od 92 predmeta od zlata i ćilibara, smeštena unutar ostataka ilirskog kneževskog tumula iz 5. veka p. n. e. Nakon detaljnih arheoloških istraživanja, crkva je konzervirana 1960. godine.','20.5274137893496','43.16201883817038','Crkva svetih apostola','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911236/tourist_attractions/24/wqqm0ca66xfczyyjqvl7.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911237/tourist_attractions/24/oiplfsqyzkbweezenwgu.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911238/tourist_attractions/24/u3eobie8nxentbmdn9yt.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911239/tourist_attractions/24/yscsf8bkldevffdsbs94.webp',3);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (25,'christian','Đurđevi stupovi nisu samo kameni zidovi crkve; oni su živa istorija i duhovno nasleđe Srbije. Njihova obnova i zaštita nisu samo akt održavanja starih kamenih zidova, već i čuvanje duha i vere koji su ovde tkani vekovima. Kroz svoje vekove postojanja, oni su svedoci vere, umetnosti i istorije Srbije i nastavljaju da budu izvor inspiracije i poštovanja. Sa obnovljenim sjajem i novim životom, Đurđevi stupovi pružaju svetli primer kako istorija i duhovnost mogu da se sačuvaju i proslave u modernom svetu.
Istorija i Značaj: Đurđevi stupovi, manastir posvećen Svetom Đorđu, predstavljaju jedan od najstarijih srpskih manastira i važan deo istorije Srbije. Podigao ih je veliki župan Stefan Nemanja u prvim godinama posle stupanja na presto velikog župana, a izgradnja je završena 1171. godine. Crkva je oslikana oko 1175. godine, a ktitorski natpis Stefana Nemanje iz 1170/1171. godine predstavlja važno svedočanstvo o počecima srpske pismenosti.
Manastir je imao istaknuto mesto u životu crkve, a njegov istorijski značaj je posebno istaknut. On je bio centar duhovnosti i obrazovanja u srednjovekovnoj Srbiji, svedočeći o bogatoj istoriji države i vere. Manastir je takođe bio važan za kraljevsku porodicu Nemanjić, što ga čini jednim od najznačajnijih manastira tog perioda.','20.497877494020443','43.16661579359568','Đurđevi stupovi','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911679/tourist_attractions/25/hyvncm9rr8n7plwyyyuc.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911680/tourist_attractions/25/cxi3ofboxxjol0tlnnzs.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911682/tourist_attractions/25/kjngrns9xdwb7f6wjxpr.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770911683/tourist_attractions/25/vfbsn9fxrvpd8ftfgfjo.jpg',4);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (26,'historic','Kula Motrilja je zajedno sa tvrđavom izgrađena sredinom 15. vijeka i za vrijeme svojeg postojanja prošla je kroz rekonstrukciju koju je nalozio sultan Abdul Aziz u 17. vijeku. Svojevremeno je unutar tvrđave postojao veliki broj objekata, a danas je samo Kula Motrilja očuvana u svojem originalnom obliku. Ova tvrđava sa svojom visinom od 15m, ispustima, mušarabijama i tri reda smaknutih greda impozantna je građevina koja je odolila Balkanskim i Svjetskim ratovima. S druge strane, ostaci nekadašnjih čardaka, džamija, magacina, kasarni i drugih objekata koji su omogućavali nesmetani život vojske nalaze se pod zemljom. Tvrđava je u to vreme postojala kao malo utvrđenje opasano rovom, zemljanim nasipom i zidom od uspravno pobodenih brvana. Najvećim delom tvrđavu su činile palisade i čardaci. Nakon Austro-turskog rata, oko 1692. godine kako svedoče sačuvani dokumenti, u okviru tvrđave podignut je unutrašnji grad da bi posle 1717. godine bile podignute najpre ugaone kule – tabije, a za vreme vladavine sultana Abdul Aziza, u drugoj polovini XIX veka, i kameni bedemi između kula. Ispred utvrđenja se nalazio šanac ispunjen vodom.','20.51700570314856','43.1391929067438','Kula Motrilja','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136172/tourist_attractions/26/wg8q7qvqz1wgoyagaqxv.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136173/tourist_attractions/26/deeesb2ytd4xpfgjfoqw.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136174/tourist_attractions/26/jsek0oew9abaczfa9dze.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136175/tourist_attractions/26/jz2na8numaet2ithmapj.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136175/tourist_attractions/26/v0yejne3fo7q2cvtoj3y.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136176/tourist_attractions/26/ovhh4sdjdppcc9awfra0.jpg',2);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (27,'historic','Isabegov hamam, poznat i kao Novopazarski stari hamam, je javno kupatilo u neposrednoj blizini Stare čaršije, na desnoj obali reke Raške u samom središtu Jeni Bazara Novog Pazara. Hamam je dao izgraditi treći beg Osmanske provincije Bosne i glavni osnivač Sarajeva i Novog Pazara, Isa-beg Isaković, u drugoj polovini 15. veka.
Isabegov hamam je primer tzv. dvojnog gradskog hamama. U zgradi su se nalazile muške i ženske prostorije, potpuno identične, odvojene po uzdužnoj simetrali osnove i pregrađene kamenim zidom. Na zgradi se nalazi jedanaest kupola različitih veličina i sa šestougaonim otvorima. Svaka prostorija prekrivena je kupolom. Na severnoj strani hamama nalazio se prostrani šadrvan koji je bio jedna vrsta čekaonice i svlačionice, dok se na južnoj strani nalazila tzv. hazna - prostorija za grejanje vode. Postojale su i tri prostorije za kupanje sa mermernim česmama i jedna prostorija za odmor od kupanja. Danas ovaj spomenik možete posetiti jer se u njemu nalazi kafić. ','20.51881742701431','43.139463461742174','Isabegov hamam','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136286/tourist_attractions/27/yxmy8hqkl2vtodtbxj49.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136288/tourist_attractions/27/foqfboeevzpf4m79u1qg.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136289/tourist_attractions/27/utjl8cu8msfym6j1bnsf.jpg',2);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (28,'natural','Gradina na Pazarištu je jedan od važnih arheoloških nalazišta koja čine deo kompleksa Stari Ras. Nalazi se na udaljenosti od 11 kilometara jugoistočno od Novog Pazara, nedaleko od manastira Sopoćani. Ovo utvrđenje se smestilo na vrhu planinskog grebena i ima karakterističan oblik nepravilnog četvorougla sa dužinom od 180 metara i širinom koja varira između 20 i 60 metara. Značajno je napomenuti da je zahvaljujući Trasnom naselju "Ras", sada omogućen lakši pristup gradini putem uređene staze koja počinje od Turističkog naselja "Ras" i proteže se na dužini od 950 metara.
Gradina je izuzetno dobro pozicionirana, s jedne strane smeštena duž vrha grebena, gde teren naglo pada, što ga čini gotovo nepristupačnim s te strane. S druge strane, utvrđenje se proteže duž blaže padine i ojačano je sa četiri manje kule i jednom većom. Njeni bedemi, široki od 1,5 do 2,2 metra, izgrađeni su od lomljenog kamena i krečnog maltera. Unutar utvrđenja nekada je stajao dvorac, naslonjen na najveću kulu. Pristup gradu bio je moguć kroz dve kapije sa zapadne i južne strane. Glavna kapija, locirana na zapadnoj strani, bila je čuvana od strane dve polukružne kule različitih dimenzija. Ovakav izgled utvrđenja najverovatnije datira iz oko 1149. godine.
Važno je napomenuti da je od 1979. godine Gradina na Pazarištu uvrštena na UNESCO-ovu listu svetske baštine, što svedoči o njenom izuzetnom arheološkom i kulturnom značaju.
Više o tvrđavi na videu:
https://www.youtube.com/watch?v=B0XQCT7IYgQ','20.4261374473561','43.10240858667287','Gradina Stari Ras','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136406/tourist_attractions/28/kqd4edjfhxj6qr0eig3s.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136407/tourist_attractions/28/sxmsbm0ilehpw1c2ywen.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136408/tourist_attractions/28/fh7plofwkadpqsowtjqk.jpg',1);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (30,'hotel','Hotel Elements se nalazi u Novom Pazaru, na 3,9 km od Novopazarske banje. U ponudi je smeštaj sa restoranom, besplatnim privatnim parkingom, barom i zajedničkim salonom. Gostima ovog smeštajnog objekta su na raspolaganju skladište za prtljag i terasa. Ovaj antialergenski objekat je udaljen 7 km od Rajčinovića banje. Sobe su klimatizovane i sadrže flat-screen TV sa kablovskim kanalima, kuvalo, tuš, fen za kosu i radni sto. Hotelske sobe imaju garderober i sopstveno kupatilo. U hotelu Elements se služi kontinentalni ili à-la-carte doručak. Najbliži aerodrom je Međunarodni aerodrom Priština, udaljen 75 km od smeštajnog objekta.
Porodicama se posebno svidela lokacija - ocenili su je sa 9,5 za boravak sa decom.','20.51268160343166','43.14353915205671','Hotel Elements','1548ed03-39e7-45c6-b435-37990961ea80','https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910522/tourist_attractions/30/m9plq6topqnynz2xnryr.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910523/tourist_attractions/30/j63iws5rv7qilivfbyrm.webp,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910540/tourist_attractions/30/a9nv5vikj1a3dbvqvzeh.webp,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770910568/tourist_attractions/30/nu2uetpanwxjsq1f9imd.jpg',12);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (33,'hotel','Restoran Druga Priča je okružen zelenilom i rekom, na splavu koji smo gradili srcem i dušom, u potpuno novom enterijeru i ambijentu koji odišu hedonizmom.','20.550371412066443','43.15563594474873','Druga priča','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1770726527/tourist_attractions/33/sujit1cz1d2sx9fnbvzn.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770726527/tourist_attractions/33/q8ddydbxccpa5qapxkm9.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770726528/tourist_attractions/33/ar50rwad39crgfkbo6l9.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770726529/tourist_attractions/33/kcg9zzpqmvzdl0m7guqa.jpg',1);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (34,'hotel','Posvećeni smo zadatku da uz potpuno novo ruho hotela ne ulepšamo samo izgled, već i da podignemo standard usluge na nivo koji dolikuje luksuznom hotelu kakav je Vrbak, pružajući svojim gostima nezaboravna i nenadmašiva iskustva.
Stati na vrh, daleko ispred konkurencije, da uz konstantan i visok nivo usluge podignemo standarde regionalnog hotelijerstva kao i postati prva asocijacija za izbor hotela kada se pomene Novi Pazar.
Hotel se nalazi u strogom centru grada u sklopu trga Isa Bega Isakovića, u neposrednoj  blizini poslovne zone banaka, javnih ustanova, velikih kompanija, butika, prodavnica obuće, marketa, modnih centara, pozorišta, bioskopa, muzeja, galerije, zelene i nadaleko čuvene pazarske modne pijace, doline konfekcije i tekstila. U središtu je najpopularnijih odredišta gradskog noćnog života Novog Pazara uz gradsko šetalište sa mnoštvo restorana, kafeterija i klubova.
SMEŠTAJNI KAPACITETI
Hotel raspolaže sa ukupno 59 smeštajnih jedinica na 3 sprata sa četiri različita tipa soba (jednokrevetne, dvokrevetne, dvokrevetne deluxe, apartmani)
Svaka od ponuđenih soba poseduje sopstveno kupatilo sa tušem kao i LCD TV mini bar, telefon i Wi-Fi.
Posebna pažnja posvećena spoju modernih pogodnosti, opreme i digitalne komunikacije i touchscreen tehnologije. Klasični šarm u prikrivanju svetlosti, umirujućim bojama, u kvalitetu i izboru posteljine i tkanina u našim sobama gostima pruža ugodno i privatno okruženje za miran noćni san.
Udobnost, smiraj i toplina su osećanja koja se doživljavaju kroz panoramski zadivljujući pogled iz hotelskih soba na centar grada i krovove Novog Pazara.
','20.516399239051353','43.140539957354065','Hotel Vrbak','e3cffb26-25f5-44e5-9680-2143844e4d5e','https://res.cloudinary.com/dp7iyoyad/image/upload/v1770816952/tourist_attractions/34/hbrkcueqtcjvyfllta9p.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770817028/tourist_attractions/34/vs0anwtxikv0ek8nth5z.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770817028/tourist_attractions/34/dlwlt3fosohwqrifmwub.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1770817985/tourist_attractions/34/ovk8iaabhtnh0dqikimj.jpg',2);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (35,'natural','U srcu jugozapadne Srbije, između planina i reka, smešten je Novi Pazar – grad bogate istorije, susreta kultura i posebne topline. Simbol tog kraja je jelek – deo tradicionalne nošnje koji ne predstavlja samo odevni predmet, već identitet, ponos i nasleđe koje se prenosi generacijama.
Jeleg u Novom Pazaru izrađivao se od kvalitetnih materijala, najčešće od čoje ili somota, ukrašen finim vezom, zlatovezom i pažljivo biranim detaljima. Svaki motiv imao je značenje – od simbola blagostanja i sreće do porodičnih i regionalnih obeležja. Nosio se u posebnim prilikama: na svadbama, verskim i porodičnim svečanostima, ali i kao svakodnevni deo gradske elegancije u prošlim vremenima.
Ženski jelek isticao je struk i sklad figure, dok je muški davao dostojanstven i otmen izgled. U spoju sa dimijama, košuljom ili maramom, stvarao je prepoznatljivu sliku pazarske čaršije – živopisne, dostojanstvene i autentične.
Danas je jelek više od tradicije – on je most između prošlosti i sadašnjosti. Mlade generacije ga ponovo otkrivaju kroz folklor, kulturne manifestacije i savremene modne interpretacije. U vremenu brzih promena, jelek ostaje podsetnik na korene, porodične vrednosti i bogatu kulturnu baštinu Novog Pazara.
Jer u svakom šavu tog jeleka utkana je priča – o gradu, o ljudima i o vremenu koje traje.
','20.56250084092854','43.029399191020715','Jeleč','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136654/tourist_attractions/35/w5hfm2dw7c3l48xpduia.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136655/tourist_attractions/35/bmc1lz0wdtqgz4nsibdl.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136655/tourist_attractions/35/otqf4wsdca3pnea6mn98.jpg',0);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (36,'restaurants','Turističko naselje “Ras“ poseduje centralnu zgradu sa restoranom od 60 mesta kao i veliku salu sa 170 mesta, baštu zatvoreno tipa sa 80 mesta, letnje bašte sa 150  kao i kafe bar sa 120 mesta.
U našem resotranu možete uživati u specijalitetima domaće i internacionalne kuhinje, kao i u velikom izboru pića. Činimo sve da otkrijete novu dimenziju uživanja u hrani i piću, čime stvaramo osećaj posebnosti za svakog gosta, kombinujući šarm prošlosti i dočaravajući sadašnjost.
Restoran je idealan za organizovanje svečanih prijema, banketa i koktel zabava, ali i venčanja i svih vaših svečanosti kako u zatvorenoj varijanti tako i na otvorenom.','20.419906771175913','43.13165653854269','Restoran Ras','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136996/tourist_attractions/36/foy5x3ld8oodhyvwrcii.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136997/tourist_attractions/36/f1skvcmojvbxhmd0qzsw.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136999/tourist_attractions/36/lgzfmn9h6qwl6a4ppnra.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772136999/tourist_attractions/36/v9aywlwdzfufeohpugjk.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137000/tourist_attractions/36/dfvffu7cwttxmbwruv5f.jpg',1);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (37,'christian','Na zapadnom obodu doline reke Raške, pored samog izvora reke, među visokim i nerodnim brdima, s pretećim kamenim liticama, kralj Uroš I (1243-1276) je, po ugledu na slavne pretke, podigao sebi grobnu crkvu posvećenu Svetoj Trojici. Naziv “Sopoćani” manastir je dobio po staroslovenskoj reči “sopot”, što znači izvor.
Spomenička celina Stari Ras sa Sopoćanima upisana je na UNESCO-vu Listu Svetske baštine 1979. godine
Manastir Sopoćani se nalazi na jedinstvenom mestu u prelepom prirodnom okruženju, na oko 15 km zapadno od Novog Pazara i nedaleko od izvora reke Raške. To je još jedan od bisera srpske srednjovekovne gradnje, i važi za jednu od najvećih svetinja u narodu. Naziv manastira vodi poreklo od staroslovenske reči ''''sopot'''' što znači izvor. Tačno vreme izgradnje ovog hrama nije poznato, jer je osnivačka povelja izgubljena, a natpis u tamburu kupole, koji je između ostalog govorio i o vremenu oslikavanja hrama Svete Trojice, oštećen je nažalost baš na mestu gde je bila zapisana godina živopisanja crkve.','20.374003395483204','43.11822570051808','Manastir Sopoćani','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137329/tourist_attractions/37/ruakdzkekfgwcb28rblu.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137331/tourist_attractions/37/z7gfjc697okumlt614jm.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137332/tourist_attractions/37/oa8vqrxsezlqhteb1nhf.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137333/tourist_attractions/37/saoymx3fptw3aur5vgib.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137334/tourist_attractions/37/d7ablllk6fedlodudduq.jpg',0);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (38,'cafe','Jazzva je prepoznatljivo mesto u gradu Novom Pazaru — kafić/bar koji spaja opuštenu atmosferu sa dobrom ponudom pića i druženja. Nalazi se u ulici Stane Bačanin i zbog svoje centralne lokacije često je središte susreta prijatelja, studenata i svih onih koji žele prijatan trenutak uz kaficu ili omiljeni napitak.
Jazzva je poznata po raznovrsnoj ponudi — od tradicionalne turske kafe i espressa do koktela i alkoholnih pića, što je čini mestom koje odgovara različitim ukusima. Posetioci često ističu lepu atmosferu, ljubazno osoblje i opušten ambijent koji pruža mesto za uživanje u razgovoru ili jednostavno pauzu u toku dana.
Ambijent Jazzve je kombinacija urbanog i prijatnog — nije previše formalno, već podseća na mesto gde se dolazi da se opusti, popije kafa sa prijateljima ili provedu lepe trenutke uz muziku i lekoviti šum grada. Cena pića je pristupačna, a mnogi ga opisuju kao jedno od omiljenih okupljališta u gradu.','20.519810725558695','43.145099961607144','Jazzva','fe5c46d8-4c05-416e-bc7d-8b18ed674d86','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137927/tourist_attractions/38/ubgweps2ybzdf244hnkm.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137928/tourist_attractions/38/ow0l7hyrj3ti9fg7ork8.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137929/tourist_attractions/38/rwcnrxlme4as0jnfxmdh.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772137930/tourist_attractions/38/dtejqjhebqu7ohu3rkyo.jpg',0);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (39,'cafe','Art cafe je jedan od prepoznatljivih kafića u Novom Pazaru koji se nalazi na adresi Stevana Nemanje 116, u delu grada gde se svakodnevno okupljaju ljubitelji dobre kafe i prijatnog provoda.
Ovaj kafić spaja opuštenu atmosferu sa kvalitetnom ponudom pića — od espresa i kapućina do raznih toplih i hladnih napitaka — i često je mesto gde se dolazi da se započne dan, popodne provede uz prijatelje ili završi večernje druženje uz smeh i ugodan razgovor. Atmosfera je opisana kao topla i prijatna, sa muzikom u pozadini koja doprinosi ležernom ugođaju.
Posetioci ističu da Art cafe ima urbani, ali domaći šarm — nije previše formalno, ali istovremeno ostavlja utisak da je mesto gde se ljudi rado vraćaju. Osoblje je obično ljubazno i uslužno, što doprinosi osećaju komfora i dobrodošlice pri svakom dolasku.','20.51955259672287','43.144471906783686','Art','74f6f9ee-ebfe-4755-b811-583449ae2397','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138389/tourist_attractions/39/j5tfnuqfbucdjvktpiyt.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138390/tourist_attractions/39/yax0dqrsyebd0eytiwgk.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138391/tourist_attractions/39/lcgxllczupsqopk9bex2.jpg',1);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (40,'cafe','Hab cafe je jedan od prepoznatljivih kafića u Novom Pazaru  u delu grada gde se svakodnevno okupljaju ljubitelji dobre kafe i prijatnog provoda.
Ovaj kafić spaja opuštenu atmosferu sa kvalitetnom ponudom pića — od espresa i kapućina do raznih toplih i hladnih napitaka — i često je mesto gde se dolazi da se započne dan, popodne provede uz prijatelje ili završi večernje druženje uz smeh i ugodan razgovor. Atmosfera je opisana kao topla i prijatna, sa muzikom u pozadini koja doprinosi ležernom ugođaju.
Posetioci ističu da Hab cafe ima urbani, ali domaći šarm — nije previše formalno, ali istovremeno ostavlja utisak da je mesto gde se ljudi rado vraćaju. Osoblje je obično ljubazno i uslužno, što doprinosi osećaju komfora i dobrodošlice pri svakom dolasku.','20.5178666967228','43.14138871290338','Hab caffe','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138725/tourist_attractions/40/ttei471q2elqmyikagpx.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138726/tourist_attractions/40/bnf2cpoldd7mdx6zjcpq.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138726/tourist_attractions/40/tclqtbe866ioi3nounxd.jpg',0);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (41,'restaurants','Art''s Diner je moderno mesto u Novom Pazaru koje je brzo postalo omiljeno među ljubiteljima dobre hrane, kafe i opuštenog provoda. Smješteno je u centralnoj ulici Stevana Nemanje, pa je lako dostupno kako lokalcima tako i posetiocima grada.
Ovaj objekat kombinuje urban i prijatan ambijent sa širim izborom jela i pića, pa nije samo „obični diner“ — već mesto gde se može uživati u doručku, ručku, laganom obroku ili večernjem izlasku. Poznat je po burgerima, sendvičima, pizzama i sendvičima inspirisanim američkom kuhinjom, ali i po klasičnim jelima poput omeleta, salata ili ukusnih uštipaka.
Hrana u Art’s Diner-u je raznovrsna — od grilovanih burgera sa sopstvenim sosom, preko pilećih specijaliteta, do mini pizza i deserata poput američkih palačinki ili mini krofni. Tome se pridružuje i širok izbor pića, od osvežavajućih sokova do kafe i bezalkoholnih napitaka, što čini ovo mesto prijatnim za različite ukuse i situacije.','20.51958765439437','43.144456506814386','Art''s diner ','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138921/tourist_attractions/41/hxw7eg6gstecjbdjdirz.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138921/tourist_attractions/41/idezqf4yvalhoz2jsbl6.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772138922/tourist_attractions/41/keujbi9zpqqvq44jxhgu.jpg',0);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (42,'restaurants','Doha Restaurant je jedan od najpoznatijih i najposećenijih restorana u Novom Pazaru, smešten na adresi 28. novembra 54. Sa ocenom oko 4.6/5 na osnovu više od 1 200 komentara, ovo je mesto koje mnogi građani i gosti grada često biraju za doručak, ručak ili večeru.
Doha je restoran koji nudi širok izbor jela — od tradicionalnih domaćih specijaliteta i predjela, preko sendviča i pizza, do steakova, teletine i riba. U meniju se mogu pronaći i raznovrsni burgeri, salate, paste, kao i omiljeni doručak sa kombinacijom jaja, mesa i salate.
Ambijent Dohe je prijatan i udoban — kao mesto gde se dolazi s porodicom, prijateljima ili poslovnim partnerima. Posetioci najčešće hvale ljubazno osoblje, profesionalnu uslugu i pristupačne cene, što doprinosi pozitivnom iskustvu bez obzira na to da li ste tu prvi put ili se vraćate po omiljeno jelo.
Restoran radi većim delom dana — od ranog jutra do kasnih večernjih sati, pa je pogodan i za doručak, ali i za večernje uživanje u dobro pripremljenoj hrani. Mnogi gosti posebno ističu i atmosferu koja je opuštena, a dekor prijatan, što čini Došu pogodnim mestom i za casual obrok i za specijalne prilike.
Iako većina komentara hvali kvalitet hrane i usluge, retki su primeri nezadovoljstva — kako kod svakog popularnog mesta, mišljenja mogu biti različita. Većina Podataka ipak pokazuje da je Doha preporučljivo mesto za isprobati raznovrsnu kuhinju u Novom Pazaru, sa odličnim kombinacijama tradicionalnih i internacionalnih jela.','20.515422837489073','43.14383197571906','Doha restoran','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772139184/tourist_attractions/42/yn99ruqtn5vvbyotmko3.webp,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772139185/tourist_attractions/42/rmrfhc0gzjjmfli8b28b.webp,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772139186/tourist_attractions/42/nlkialjlazszidbrvnak.webp,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772139187/tourist_attractions/42/mtjzbfka9rseebcdocou.jpg',0);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (43,'Islamic','Altun-alem džamija (džamija sa zlatnim alemom - dragim kamenom) nalazi se u Novom Pazaru, Srbija, u Prvomajskoj ulici broj 79. Izgradio ju je osmanlija Muslihudin Abdulgani početkom 16. veka. Ona predstavlja retko remek-delo islamske arhitekture i pod zaštitom je države od 1979. godine.
Altun-alem džamiju je u prvoj polovini 16. veka izgradio osmanlijski neimar Muslihudin Abdulgani, poznat i pod imenom Mujezin hodža al-Medini. On je izgradio mnoge građevine na Balkanu. U Skoplju je podigao Kuršumli han, džamiju, obnovio je jedan hamam i posedovao je nekoliko kuća i dućana. Izgradio je džamiju i karavansaraj u Mažićima kod Zvečana. U Vakufnami iz 1550. godine mogu se naći svi njegovi projekti na teritoriji Novog Pazara: Altun-alem džamija, mekteb na tlu džamijskog kompleksa, tri kuće za boravk imama, han, šest dućana pored hamama, šest kožarskih dućana u Tabačkoj čaršiji na obali Raške, sedam mlinova pored mosta (jedan od njih je bio sa pet vitlova). Sasvim je sigurno da je graditelj Altun-alem džamije bio bogat čim je izgradio toliko objekata, ne samo sakralnih. Međutim, on je bio i vrlo obrazovan i ucen. To potvrđuje njegovo zvanje - Mevlana (Mevlana Muslihudin Efendija), to je počasno zvanje koje su mogli nositi samo istaknuti islamski učenjaci i filozofi.','20.518567366036898','43.13681654742798','Altun alem džamija','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772139465/tourist_attractions/43/lzrzqfm6uci3vicukpij.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772139466/tourist_attractions/43/hsg0oo3zcowdot3m3nnz.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772139467/tourist_attractions/43/hyrbtdyha1zkie99mshs.jpg',0);
INSERT INTO "TouristAttractions" ("Id","Category","Description","Latitude","Longitude","Name","OwnerId","Photos","ViewCount") VALUES (44,'cafe','Nalazimo se u srcu Novog Pazara, unutar kulturno istorijskog objekta Amir-aginog hana, čineći nas posebnom destinacijom za sve ljubitelje kafe. Kroz autentičan ambijent i vrhunsku uslugu, oživljavamo istorijski značaj ove lokacije i duh prošlih vremena. Neodoljiva kombinacija osvežavajuće mešavine kafe, mleka i karamela, savršena poslastica za hedoniste i naša najprodavanija kafa.
HANCOFFEE je pokrenuo pravu revoluciju hladnih kafa za poneti u Novom Pazaru. Naša jedinstvena ponuda hladnih napitaka, osvojila je srca mnogih i postala sinonim za našu kafeteriju. Naša strast za inovacijama i kreativnosti dovela je do našeg prepoznatljivog uspeha. 
Amir-agin han, smešten u centru Novog Pazara, predstavlja izuzetan kulturno-istorijski objekat sa 300+ godina bogatom prošlošću
Ovaj čuveni han simbolizuje duh trgovine i gostoprimstva koji je vekovima bio prisutan na ovim prostorima. Kao deo naše kafeterije, mi oživljavamo istorijski značaj Amir-aginog hana i stvaramo jedinstvenu atmosferu koja spaja prošlost i sadašnjost, pružajući našim posetiocima autentično iskustvo.
','20.51734935254416','43.1410785419424','Han caffe','1c44ed34-5771-48d1-b028-1c3412024120','https://res.cloudinary.com/dp7iyoyad/image/upload/v1772276301/tourist_attractions/44/a6f0sw48x2eoum7n5xar.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772276302/tourist_attractions/44/m5p9jku134ht0wasybjt.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772276302/tourist_attractions/44/aghpuvuljayciqzgilzl.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772276303/tourist_attractions/44/y0gyrfcwknbdq8zw2dkx.jpg,https://res.cloudinary.com/dp7iyoyad/image/upload/v1772276303/tourist_attractions/44/fbgujqueqibuay9rttdq.jpg',0);
-- AspNetRoleClaims
-- AspNetUserClaims
-- AspNetUserLogins
-- AspNetUserRoles
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('1548ed03-39e7-45c6-b435-37990961ea80','3fd8fa8b-b1c7-49b3-b20d-d827b0c5e044');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('74f6f9ee-ebfe-4755-b811-583449ae2397','3fd8fa8b-b1c7-49b3-b20d-d827b0c5e044');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('aa8988ae-bb40-424e-9654-4cfc04ceebf0','3fd8fa8b-b1c7-49b3-b20d-d827b0c5e044');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('e3cffb26-25f5-44e5-9680-2143844e4d5e','3fd8fa8b-b1c7-49b3-b20d-d827b0c5e044');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('fe5c46d8-4c05-416e-bc7d-8b18ed674d86','3fd8fa8b-b1c7-49b3-b20d-d827b0c5e044');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('1c44ed34-5771-48d1-b028-1c3412024120','d052c60a-0c4d-49f9-aa0d-346499b6ae90');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('785f4d30-7005-4b07-9ef5-a46c0cdd1db3','d052c60a-0c4d-49f9-aa0d-346499b6ae90');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('8d7364c7-5526-4ed4-bb09-24114c811411','dcb58a84-3b9f-4566-b991-0858df135c21');
INSERT INTO "AspNetUserRoles" ("UserId","RoleId") VALUES ('a4f6481f-223e-44fb-86ef-bd866e7dc1ea','dcb58a84-3b9f-4566-b991-0858df135c21');
-- AspNetUserTokens
-- Reviews
INSERT INTO "Reviews" ("Id","Comment","CreatedOn","Rating","TouristAttractionId","UserId") VALUES (17,'supeer','2025-01-13T21:39:09.3953610',4,18,'a4f6481f-223e-44fb-86ef-bd866e7dc1ea');
INSERT INTO "Reviews" ("Id","Comment","CreatedOn","Rating","TouristAttractionId","UserId") VALUES (18,'supeer','2025-01-13T22:15:03.6573934',5,24,'a4f6481f-223e-44fb-86ef-bd866e7dc1ea');
INSERT INTO "Reviews" ("Id","Comment","CreatedOn","Rating","TouristAttractionId","UserId") VALUES (28,'super','2026-02-12T15:19:38.1800179',4,30,'a4f6481f-223e-44fb-86ef-bd866e7dc1ea');
INSERT INTO "Reviews" ("Id","Comment","CreatedOn","Rating","TouristAttractionId","UserId") VALUES (30,'Prelepo mesto, istorijski zanimljivo.','2026-02-12T16:10:48.9944962',4,26,'8d7364c7-5526-4ed4-bb09-24114c811411');
-- Portfolios
INSERT INTO "Portfolios" ("UserId","TouristAttractionId") VALUES ('1c44ed34-5771-48d1-b028-1c3412024120',3);
INSERT INTO "Portfolios" ("UserId","TouristAttractionId") VALUES ('a4f6481f-223e-44fb-86ef-bd866e7dc1ea',18);
INSERT INTO "Portfolios" ("UserId","TouristAttractionId") VALUES ('785f4d30-7005-4b07-9ef5-a46c0cdd1db3',24);
INSERT INTO "Portfolios" ("UserId","TouristAttractionId") VALUES ('a4f6481f-223e-44fb-86ef-bd866e7dc1ea',24);
INSERT INTO "Portfolios" ("UserId","TouristAttractionId") VALUES ('a4f6481f-223e-44fb-86ef-bd866e7dc1ea',30);
-- __EFMigrationsHistory
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20241203140718_AddedPortfolio','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20241204154157_Review1to1','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20241218130042_InitialCreate','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20241220111045_AddIsApprovedToUser','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20241224182927_AddedLocation','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20241224183656_Initial','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20250104134049_AddCreatedAttractionIdToUser','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20250104134938_remove','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20250104141049_AddOwnerIdToTouristAttraction','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20260211143448_AddViewCountToAttractions','8.0.10');
INSERT INTO "__EFMigrationsHistory" ("MigrationId","ProductVersion") VALUES ('20260211153932_AddViewCountToAttractions','8.0.10');
SELECT setval(pg_get_serial_sequence('"TouristAttractions"','Id'), COALESCE(MAX("Id"),1), true) FROM "TouristAttractions";
SELECT setval(pg_get_serial_sequence('"Reviews"','Id'), COALESCE(MAX("Id"),1), true) FROM "Reviews";
SELECT setval(pg_get_serial_sequence('"AspNetRoleClaims"','Id'), COALESCE(MAX("Id"),1), true) FROM "AspNetRoleClaims";
SELECT setval(pg_get_serial_sequence('"AspNetUserClaims"','Id'), COALESCE(MAX("Id"),1), true) FROM "AspNetUserClaims";
COMMIT;
